---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Managed Prometheus
      type: prometheus
      url: https://aps-workspaces.ap-southeast-1.amazonaws.com/workspaces/ws-991b6bb6-5c17-4af9-b73b-54404f3c3cc8/
      jsonData:
        sigV4Auth: true
        sigV4Region: ap-southeast-1
        sigV4AuthType: default
