---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Managed Prometheus
      type: prometheus
      url: https://aps-workspaces.ap-southeast-1.amazonaws.com/workspaces/ws-c2ada971-dbdb-4692-8ff5-1b37368f1898/
      jsonData:
        sigV4Auth: true
        sigV4Region: ap-southeast-1
        sigV4AuthType: default
